apiVersion: v1
kind: Service
metadata:
  name: documents
  namespace: archivofiel
spec:
  selector:
    app: documents
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP