apiVersion: apps/v1
kind: Deployment
metadata:
  name: transfers-deployment
  labels:
    app: transfers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transfers
  template:
    metadata:
      labels:
        app: transfers
    spec:
      containers:
      - name: transfers
        image: camiloet99/transfers:latest
        ports:
        - containerPort: 8080
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "localhost:9092" # Actualiza si tu Kafka está en otro host
        - name: KAFKA_GROUP_ID
          value: "distribuidos-group"
        - name: KAFKA_TOPIC_NAME
          value: "transfers-topic"
        - name: DISABLE_SSL_CERT_VALIDATION
          value: "true"
        - name: DOCUMENTS_DOMAIN
          value: "http://documents.archivofiel.svc.cluster.local"
        - name: AUTHENTICATION_DOMAIN
          value: "http://authentication.archivofiel.svc.cluster.local"
        - name: SERVICE_RETRY_MAX_ATTEMPTS
          value: "2"
        - name: MAX_PAYLOAD_SIZE_IN_MB
          value: "10"
        resources:
          limits:
            memory: "128Mi"
            cpu: "20m"
          requests:
            memory: "128Mi"
            cpu: "20m"
