apiVersion: apps/v1
kind: Deployment
metadata:
  name: requests
  namespace: archivofiel
  labels:
    app: requests
spec:
  replicas: 2
  selector:
    matchLabels:
      app: requests
  template:
    metadata:
      labels:
        app: requests
    spec:
      containers:
      - name: requests
        image: myrepo/requests:latest  # Reemplaza con la imagen adecuada
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URL
          value: "jdbc:mysql://mydb/requests"

